server:
  port: 8081

undertow:
    accesslog:
      enabled: false
    io-threads: 4 #设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接,默认取CPU核心数量

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    url: jdbc:sqlite:/develop/data/other/chat.db
    type: com.zaxxer.hikari.HikariDataSource

  application:
      name: xxmpchat


#文件信息配置
file:
  img:
    savePath: /tmp/chen
    showPath: /tmp/

logging:
  level:
    com.bai.front.dao.mapper: debug
